# PyTorch

## [1] Tensor 생성

In [1]:
import torch

In [3]:
# torch 버전확인
torch.__version__

'1.12.1'

In [4]:
# [기본] tebsor(data)
t1=torch.tensor([1,2,3])

In [5]:
type(t1),t1.shape,t1.dtype,t1.device

(torch.Tensor, torch.Size([3]), torch.int64, device(type='cpu'))

In [22]:
# 타입설정
t2=torch.tensor([1,2,3],dtype=torch.int32)
type(t2),t2.shape,t2.dtype,t2.device

(torch.Tensor, torch.Size([3]), torch.int32, device(type='cpu'))

In [14]:
t3=torch.tensor([[1.,2,3],[1,2,2]])
type(t3),t3.shape,t3.dtype,t3.device

(torch.Tensor, torch.Size([2, 3]), torch.float32, device(type='cpu'))

In [17]:
t4=torch.ones(size=(10,))
t4

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
t5=torch.ones(size=(10,3))
t5

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [20]:
t6=torch.zeros(size=(10,3))
t6

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [21]:
# 같은형태의 tensor을 불러와 값 집어넣기
torch.ones_like(t6)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [24]:
# 0~1사이 값을 t3와 같은 형태로 생성
torch.rand_like(t3)

tensor([[0.6319, 0.8882, 0.1455],
        [0.4146, 0.3045, 0.0895]])

## Indexing & Slicing

In [34]:
t3

tensor([[1., 2., 3.],
        [1., 2., 2.]])

In [31]:
t3.ndim,t3.shape

(2, torch.Size([2, 3]))

In [28]:
# 0행
t3[0]

tensor([1., 2., 3.])

In [29]:
# 1행
t3[1]

tensor([1., 2., 2.])

In [32]:
# 0열
t3[:,0]

tensor([1., 1.])

In [35]:
# 2열
t3[:,2]

tensor([3., 2.])

In [33]:
# 0행 1열
t3[0,1]

tensor(2.)

In [36]:
# 행렬곱
y1=t3.T
y2=t3
torch.matmul(y1,y2)

tensor([[ 2.,  4.,  5.],
        [ 4.,  8., 10.],
        [ 5., 10., 13.]])

In [40]:
# 그냥 곱
y1=t3
y2=t3

print(torch.mul(y1,y2))
print(y1.mul(y2))

tensor([[1., 4., 9.],
        [1., 4., 4.]])
tensor([[1., 4., 9.],
        [1., 4., 4.]])


In [42]:
# 최대값
t3.max(),t3[1].max()

(tensor(3.), tensor(2.))

In [43]:
# 최소값
t3.min(),t3[1].min()

(tensor(1.), tensor(1.))

In [46]:
# 모든원소에 값 더하기
t3.add_(10)
t3

# t3의 값이 변경 된다. => 원본 변경

tensor([[31., 32., 33.],
        [31., 32., 32.]])

In [48]:
# 배열로 변경
t3_arr=t3.numpy()
t3_arr

array([[31., 32., 33.],
       [31., 32., 32.]], dtype=float32)

In [51]:
torch.cuda.is_available()

False