In [36]:
# 모듈 로딩 ---------------------------------------
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import numpy as np

In [37]:
# 데이터 로딩 ------------------------------------

iris= load_iris()

In [5]:
data=iris.data

In [6]:
target=iris.target

In [38]:
data.shape, target.shape , type(data), type(target)

((150, 4), (150,), numpy.ndarray, numpy.ndarray)

In [39]:
# 모델 생성 ----------------------------------------
model=LogisticRegression(max_iter=500)

In [40]:
# 학습 ---------------------------------------------
model.fit(data, target)

LogisticRegression(max_iter=500)

In [41]:
# coef_  : 선형계수 즉 기울지w ==> 특성 Feature 개수 만큼 coef_ 
# coef_, intercept_            ==> 분류 개수 만큼 
print('classes_   :', model.classes_)
print('coef_      :', model.coef_)
print('intercept_ :', model.intercept_)

classes_   : [0 1 2]
coef_      : [[-0.42340889  0.967222   -2.51717294 -1.07951333]
 [ 0.53440818 -0.32161354 -0.2065182  -0.9441596 ]
 [-0.1109993  -0.64560846  2.72369114  2.02367293]]
intercept_ : [  9.84977927   2.23796266 -12.08774193]


In [18]:
data[145:]

array([[6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [24]:
new_data=[6.7, 3. , 5.2, 2.3]

ret=model.decision_function([new_data])
print(ret)

[[-5.65757422  1.60819516  4.04937906]]


In [34]:
from scipy.special import softmax

# y=aw1+bw2+cw3+dw4+b
values=[]
for i in range(3):
    y=model.coef_[i][0]*new_data[0] + \
      model.coef_[i][1]*new_data[1] + \
      model.coef_[i][2]*new_data[2] + \
      model.coef_[i][3]*new_data[3] +model.intercept_[i]
    print('y =', y, end='  ')
    values.append(y)
    
# softmax()에 전달하기 위해 변환    
arrValue=np.array(values)

y = -5.657574223601058  y = 1.6081951619123136  y = 4.0493790616893115  

In [35]:
# 분류 항목별 나온 값을 확률값으로 변환하여 반환
from scipy.special import softmax

np.round(softmax(ret), 3),   np.round(softmax(arrValue), 3)

(array([[0.  , 0.08, 0.92]]), array([0.  , 0.08, 0.92]))